language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mock' ]; then cd .. && eval "mv $currentfolder generator-mock" && cd generator-mock; fi

